id: P533EADA6
initial_creation_type: input
source_metadata:
  title: Longevity Series
  language: bo
  description: 'Texts on the theme of longevity, including ritual practices to accomplish
    long life (tshe sgrub):'
  volume:
    759cf421f9bc497cb21e209ea71b9273:
      title: The Dhāraṇī of Amitāyus
      parent: Canonical Texts
    a7dec789572a439e9b700d564d5e4e8b:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Canonical Texts
    98cab8bddbdc450fa55bad1486ce403f:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    4eb367cdebe640f98c2293fcf6e4659b:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Practices
    466fea6cd4374f4f937387136f2b6398:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Practices
    136cb283b4bd4409a3a7763a2c56a31f:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Practices
    5657d4064faf4ce3939c69f853f21628:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    5791224ef6e144f284279c9b03401f82:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Practices
    2f124e3e6d214741957af172feb4fdfe:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Recitation Guides
    989ed7015c5a4ff9be727c1197a4d45d:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    2b1b06c931984e1da7c94e87821cba7a:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
created_at: '2022-03-01T04:28:01.286914'
last_modified_at: '2022-03-01T04:28:01.286917'
